//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agate.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agate.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should start playing the movie now.
        /// </summary>
        public static string AlertMessageMovieShouldPlayMovieNow {
            get {
                return ResourceManager.GetString("AlertMessageMovieShouldPlayMovieNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Tapped!.
        /// </summary>
        public static string AlertTitleMovieTapped {
            get {
                return ResourceManager.GetString("AlertTitleMovieTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy it now!.
        /// </summary>
        public static string BannerBodyEnjoyItNow {
            get {
                return ResourceManager.GetString("BannerBodyEnjoyItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25% discount.
        /// </summary>
        public static string BannerTitle25DiscOff {
            get {
                return ResourceManager.GetString("BannerTitle25DiscOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string ButtonAddComment {
            get {
                return ResourceManager.GetString("ButtonAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string ButtonAddToCart {
            get {
                return ResourceManager.GetString("ButtonAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a user? Login now.
        /// </summary>
        public static string ButtonAlreadyUserLoginNow {
            get {
                return ResourceManager.GetString("ButtonAlreadyUserLoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse our samples.
        /// </summary>
        public static string ButtonBrowseOurSamples {
            get {
                return ResourceManager.GetString("ButtonBrowseOurSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ButtonDefault {
            get {
                return ResourceManager.GetString("ButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string ButtonDeleteAccount {
            get {
                return ResourceManager.GetString("ButtonDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string ButtonMore {
            get {
                return ResourceManager.GetString("ButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Movie.
        /// </summary>
        public static string ButtonPlayMovie {
            get {
                return ResourceManager.GetString("ButtonPlayMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Action.
        /// </summary>
        public static string ButtonPrimaryAction {
            get {
                return ResourceManager.GetString("ButtonPrimaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Action.
        /// </summary>
        public static string ButtonSecondaryAction {
            get {
                return ResourceManager.GetString("ButtonSecondaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See our walkthrough.
        /// </summary>
        public static string ButtonSeeOurWalkThrough {
            get {
                return ResourceManager.GetString("ButtonSeeOurWalkThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m an Editor 
        ///and I love multiple lines! ;).
        /// </summary>
        public static string EditorSampleText {
            get {
                return ResourceManager.GetString("EditorSampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string EntryCellPlaceholderPhoneNumber {
            get {
                return ResourceManager.GetString("EntryCellPlaceholderPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to robert.stainford@uxdivers.com.
        /// </summary>
        public static string EntryCellSampleEmail {
            get {
                return ResourceManager.GetString("EntryCellSampleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail.
        /// </summary>
        public static string ErrorPleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("ErrorPleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 days logged in.
        /// </summary>
        public static string ImageCellDetailDaysLoggedIn {
            get {
                return ResourceManager.GetString("ImageCellDetailDaysLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS Studio PartnerWe are a team of passionate UX/UI Designers and Developers with only one mission: help developers make appealing good applications better and 
        ///faster while we have fun doing what we love..
        /// </summary>
        public static string LabelAboutUsText {
            get {
                return ResourceManager.GetString("LabelAboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivityIndicators.
        /// </summary>
        public static string LabelActivityIndicators {
            get {
                return ResourceManager.GetString("LabelActivityIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artina Buttons.
        /// </summary>
        public static string LabelArtinaButtons {
            get {
                return ResourceManager.GetString("LabelArtinaButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artina Entry.
        /// </summary>
        public static string LabelArtinaEntry {
            get {
                return ResourceManager.GetString("LabelArtinaEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string LabelBadge {
            get {
                return ResourceManager.GetString("LabelBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandBlock.
        /// </summary>
        public static string LabelBrandBlock {
            get {
                return ResourceManager.GetString("LabelBrandBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        public static string LabelButtons {
            get {
                return ResourceManager.GetString("LabelButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CircleImages.
        /// </summary>
        public static string LabelCircleImages {
            get {
                return ResourceManager.GetString("LabelCircleImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Image Cache.
        /// </summary>
        public static string LabelClearImageCache {
            get {
                return ResourceManager.GetString("LabelClearImageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string LabelCredits {
            get {
                return ResourceManager.GetString("LabelCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note the Menu displayed on top ;).
        /// </summary>
        public static string LabelCustomavBarNoteMenu {
            get {
                return ResourceManager.GetString("LabelCustomavBarNoteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom NavBar.
        /// </summary>
        public static string LabelCustomNavBar {
            get {
                return ResourceManager.GetString("LabelCustomNavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NavBar on this page is totally custom which means you could add as many icons as you need and combine it with other views such as badges, etc..
        /// </summary>
        public static string LabelCustomNavBarText {
            get {
                return ResourceManager.GetString("LabelCustomNavBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Global issues.
        /// </summary>
        public static string LabelDisplayGlobalIssues {
            get {
                return ResourceManager.GetString("LabelDisplayGlobalIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries And Editors.
        /// </summary>
        public static string LabelEntriesAndEditors {
            get {
                return ResourceManager.GetString("LabelEntriesAndEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string LabelForgotYourPassword {
            get {
                return ResourceManager.GetString("LabelForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry type your email here and we will recover it for you..
        /// </summary>
        public static string LabelForgotYourPasswordExplained {
            get {
                return ResourceManager.GetString("LabelForgotYourPasswordExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        public static string LabelFrames {
            get {
                return ResourceManager.GetString("LabelFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView and SearchBar.
        /// </summary>
        public static string LabelListViewAndSearchBar {
            get {
                return ResourceManager.GetString("LabelListViewAndSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or register using your email and password..
        /// </summary>
        public static string LabelLoginOrRegisterUsinMailOrPass {
            get {
                return ResourceManager.GetString("LabelLoginOrRegisterUsinMailOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need custom animations?.
        /// </summary>
        public static string LabelNeedCustomAnimations {
            get {
                return ResourceManager.GetString("LabelNeedCustomAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or connect with.
        /// </summary>
        public static string LabelOrConnectWith {
            get {
                return ResourceManager.GetString("LabelOrConnectWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        public static string LabelOurProducts {
            get {
                return ResourceManager.GetString("LabelOurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial UI Kit and Gorilla Player for Xamarin.Forms
        ///had been helping developers build better and good looking apps faster since 2015.
        ///Stay tunned we have more surprises coming soon….
        /// </summary>
        public static string LabelOurProductsLongText {
            get {
                return ResourceManager.GetString("LabelOurProductsLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passion driven designer and developer. Frustrated musician and father of two..
        /// </summary>
        public static string LabelPassionDrivenDesigner {
            get {
                return ResourceManager.GetString("LabelPassionDrivenDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string LabelPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("LabelPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography is my passion. Black and white is the way I see the world..
        /// </summary>
        public static string LabelPhotographyIsMyPassion {
            get {
                return ResourceManager.GetString("LabelPhotographyIsMyPassion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickers.
        /// </summary>
        public static string LabelPickers {
            get {
                return ResourceManager.GetString("LabelPickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LabelPlaceholderEmail {
            get {
                return ResourceManager.GetString("LabelPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressBars.
        /// </summary>
        public static string LabelProgressBars {
            get {
                return ResourceManager.GetString("LabelProgressBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string LabelRegisterNow {
            get {
                return ResourceManager.GetString("LabelRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now and enjoy the pleasures of the demo..
        /// </summary>
        public static string LabelRegisterNowAndEnjoy {
            get {
                return ResourceManager.GetString("LabelRegisterNowAndEnjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string LabelRepeatPassword {
            get {
                return ResourceManager.GetString("LabelRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoundedLabel.
        /// </summary>
        public static string LabelRoundedLabel {
            get {
                return ResourceManager.GetString("LabelRoundedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        public static string LabelSliders {
            get {
                return ResourceManager.GetString("LabelSliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks.
        /// </summary>
        public static string LabelSpecialThanks {
            get {
                return ResourceManager.GetString("LabelSpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches.
        /// </summary>
        public static string LabelSwitches {
            get {
                return ResourceManager.GetString("LabelSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take your app to the next level with Grial UI Kit..
        /// </summary>
        public static string LabelTakeYourAppToNextLevel {
            get {
                return ResourceManager.GetString("LabelTakeYourAppToNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing here my friend :).
        /// </summary>
        public static string LabelThereIsNothingHere {
            get {
                return ResourceManager.GetString("LabelThereIsNothingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a frame containing a Label control.
        /// </summary>
        public static string LabelThisIsAFrameDescription {
            get {
                return ResourceManager.GetString("LabelThisIsAFrameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your credentials to login..
        /// </summary>
        public static string LabelUseCredentialsToLogin {
            get {
                return ResourceManager.GetString("LabelUseCredentialsToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like my toast done on one side..
        /// </summary>
        public static string LabelUserDescriptionVariant {
            get {
                return ResourceManager.GetString("LabelUserDescriptionVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Entry Error Style.
        /// </summary>
        public static string LabelValidationEntryErrorStyle {
            get {
                return ResourceManager.GetString("LabelValidationEntryErrorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS Studio Partner.
        /// </summary>
        public static string LabelVisualStudioPartner {
            get {
                return ResourceManager.GetString("LabelVisualStudioPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As partners of the greatest IDE ever, we are commited to deliver high quality products that really help devs to achieve their best..
        /// </summary>
        public static string LabelVisualStudioPartnerLongText {
            get {
                return ResourceManager.GetString("LabelVisualStudioPartnerLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a team of passionate UX/UI Designers and Developers with only one mission: help developers make appealing good applications better and 
        ///faster while we have fun doing what we love..
        /// </summary>
        public static string LabelWeAreATeamOfPassionate {
            get {
                return ResourceManager.GetString("LabelWeAreATeamOfPassionate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Grial.Starter.
        /// </summary>
        public static string LabelWelcomeToGrialStarter {
            get {
                return ResourceManager.GetString("LabelWelcomeToGrialStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Grial Starter. You are all setup and ready to rock!.
        /// </summary>
        public static string LabelWelcomeToGrialStarterDescription {
            get {
                return ResourceManager.GetString("LabelWelcomeToGrialStarterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes! Grial UI Kit now supports Lottie Animations out of the box..
        /// </summary>
        public static string LabelYesGrialSupportsLottie {
            get {
                return ResourceManager.GetString("LabelYesGrialSupportsLottie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons Dashboard.
        /// </summary>
        public static string PageMenuTitleDashboardIcons {
            get {
                return ResourceManager.GetString("PageMenuTitleDashboardIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic About Page.
        /// </summary>
        public static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string PageTitleAnimation {
            get {
                return ResourceManager.GetString("PageTitleAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles Classic View.
        /// </summary>
        public static string PageTitleArticleClassicView {
            get {
                return ResourceManager.GetString("PageTitleArticleClassicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles List.
        /// </summary>
        public static string PageTitleArticleList {
            get {
                return ResourceManager.GetString("PageTitleArticleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles Feed.
        /// </summary>
        public static string PageTitleArticlesFeed {
            get {
                return ResourceManager.GetString("PageTitleArticlesFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles List Variant.
        /// </summary>
        public static string PageTitleArticlesListVariant {
            get {
                return ResourceManager.GetString("PageTitleArticlesListVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article View.
        /// </summary>
        public static string PageTitleArticleView {
            get {
                return ResourceManager.GetString("PageTitleArticleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards List.
        /// </summary>
        public static string PageTitleCardsList {
            get {
                return ResourceManager.GetString("PageTitleCardsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories List Flat.
        /// </summary>
        public static string PageTitleCategoriesListFlat {
            get {
                return ResourceManager.GetString("PageTitleCategoriesListFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Categories.
        /// </summary>
        public static string PageTitleCategoriesListWithIcons {
            get {
                return ResourceManager.GetString("PageTitleCategoriesListWithIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Categories.
        /// </summary>
        public static string PageTitleCategoryListImages {
            get {
                return ResourceManager.GetString("PageTitleCategoryListImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Messages List.
        /// </summary>
        public static string PageTitleChatMessageList {
            get {
                return ResourceManager.GetString("PageTitleChatMessageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Timeline.
        /// </summary>
        public static string PageTitleChatTimeLine {
            get {
                return ResourceManager.GetString("PageTitleChatTimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial Common Views.
        /// </summary>
        public static string PageTitleCommonViews {
            get {
                return ResourceManager.GetString("PageTitleCommonViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Activity Indicator.
        /// </summary>
        public static string PageTitleCustomActivityIndicator {
            get {
                return ResourceManager.GetString("PageTitleCustomActivityIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom NavBar.
        /// </summary>
        public static string PageTitleCustomNavBar {
            get {
                return ResourceManager.GetString("PageTitleCustomNavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Renderers.
        /// </summary>
        public static string PageTitleCustomRenderers {
            get {
                return ResourceManager.GetString("PageTitleCustomRenderers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Settings Page.
        /// </summary>
        public static string PageTitleCustomSettings {
            get {
                return ResourceManager.GetString("PageTitleCustomSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Cards.
        /// </summary>
        public static string PageTitleDashboardCards {
            get {
                return ResourceManager.GetString("PageTitleDashboardCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Dashboard.
        /// </summary>
        public static string PageTitleDashboardFlat {
            get {
                return ResourceManager.GetString("PageTitleDashboardFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string PageTitleDashboardIcons {
            get {
                return ResourceManager.GetString("PageTitleDashboardIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Multiple Scroll.
        /// </summary>
        public static string PageTitleDashboardMultipleScroll {
            get {
                return ResourceManager.GetString("PageTitleDashboardMultipleScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Tiles.
        /// </summary>
        public static string PageTitleDashboardMultipleTiles {
            get {
                return ResourceManager.GetString("PageTitleDashboardMultipleTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Scrollable.
        /// </summary>
        public static string PageTitleDashboardScrollable {
            get {
                return ResourceManager.GetString("PageTitleDashboardScrollable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Dashboard.
        /// </summary>
        public static string PageTitleDashboardWithImages {
            get {
                return ResourceManager.GetString("PageTitleDashboardWithImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Timeline.
        /// </summary>
        public static string PageTitleDocumentTimeline {
            get {
                return ResourceManager.GetString("PageTitleDocumentTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty State.
        /// </summary>
        public static string PageTitleEmptyState {
            get {
                return ResourceManager.GetString("PageTitleEmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Page News.
        /// </summary>
        public static string PageTitleFrontPageNews {
            get {
                return ResourceManager.GetString("PageTitleFrontPageNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string PageTitleLogin {
            get {
                return ResourceManager.GetString("PageTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string PageTitleMainMenu {
            get {
                return ResourceManager.GetString("PageTitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string PageTitleMessages {
            get {
                return ResourceManager.GetString("PageTitleMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Selection.
        /// </summary>
        public static string PageTitleMovieSelection {
            get {
                return ResourceManager.GetString("PageTitleMovieSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Controls.
        /// </summary>
        public static string PageTitleNativeControls {
            get {
                return ResourceManager.GetString("PageTitleNativeControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        public static string PageTitlePasswordRecovery {
            get {
                return ResourceManager.GetString("PageTitlePasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Grid.
        /// </summary>
        public static string PageTitleProductGrid {
            get {
                return ResourceManager.GetString("PageTitleProductGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Grid Variant.
        /// </summary>
        public static string PageTitleProductGridVariant {
            get {
                return ResourceManager.GetString("PageTitleProductGridVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Order.
        /// </summary>
        public static string PageTitleProductOrder {
            get {
                return ResourceManager.GetString("PageTitleProductOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Catalog.
        /// </summary>
        public static string PageTitleProductsCatalog {
            get {
                return ResourceManager.GetString("PageTitleProductsCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string PageTitleProfile {
            get {
                return ResourceManager.GetString("PageTitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Chat List.
        /// </summary>
        public static string PageTitleRecentChatList {
            get {
                return ResourceManager.GetString("PageTitleRecentChatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive Helpers.
        /// </summary>
        public static string PageTitleResponsiveHelpers {
            get {
                return ResourceManager.GetString("PageTitleResponsiveHelpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Page.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string PageTitleSignup {
            get {
                return ResourceManager.GetString("PageTitleSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Login.
        /// </summary>
        public static string PageTitleSimpleLogin {
            get {
                return ResourceManager.GetString("PageTitleSimpleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Sign Up.
        /// </summary>
        public static string PageTitleSimpleSignup {
            get {
                return ResourceManager.GetString("PageTitleSimpleSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string PageTitleSocial {
            get {
                return ResourceManager.GetString("PageTitleSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Variant.
        /// </summary>
        public static string PageTitleSocialVariant {
            get {
                return ResourceManager.GetString("PageTitleSocialVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed Page.
        /// </summary>
        public static string PageTitleTabbedPage {
            get {
                return ResourceManager.GetString("PageTitleTabbedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial TabControl Sample Page.
        /// </summary>
        public static string PageTitleTabControl {
            get {
                return ResourceManager.GetString("PageTitleTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Icons Preview.
        /// </summary>
        public static string PageTitleThemeFontIcons {
            get {
                return ResourceManager.GetString("PageTitleThemeFontIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial Themes Preview.
        /// </summary>
        public static string PageTitleThemesPreview {
            get {
                return ResourceManager.GetString("PageTitleThemesPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string PageTitleTimeline {
            get {
                return ResourceManager.GetString("PageTitleTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string PageTitleTitleNotifications {
            get {
                return ResourceManager.GetString("PageTitleTitleNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView.
        /// </summary>
        public static string PageTitleWebview {
            get {
                return ResourceManager.GetString("PageTitleWebview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Page.
        /// </summary>
        public static string PageTitleWelcome {
            get {
                return ResourceManager.GetString("PageTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Starter.
        /// </summary>
        public static string PageTitleWelcomeStarter {
            get {
                return ResourceManager.GetString("PageTitleWelcomeStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a Picker!.
        /// </summary>
        public static string PickerTitleSample {
            get {
                return ResourceManager.GetString("PickerTitleSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAST.
        /// </summary>
        public static string RoundedLabelCast {
            get {
                return ResourceManager.GetString("RoundedLabelCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTOR.
        /// </summary>
        public static string RoundedLabelDirector {
            get {
                return ResourceManager.GetString("RoundedLabelDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial Rounded Label Sample.
        /// </summary>
        public static string RoundedLabelTextSample {
            get {
                return ResourceManager.GetString("RoundedLabelTextSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial Movies.
        /// </summary>
        public static string SampleDashboardGrialMovies {
            get {
                return ResourceManager.GetString("SampleDashboardGrialMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Carousel.
        /// </summary>
        public static string SampleProductCarousel {
            get {
                return ResourceManager.GetString("SampleProductCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product FullScreen.
        /// </summary>
        public static string SampleProductFullscreen {
            get {
                return ResourceManager.GetString("SampleProductFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Item View.
        /// </summary>
        public static string SampleProductItemView {
            get {
                return ResourceManager.GetString("SampleProductItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Page.
        /// </summary>
        public static string SampleTitleRootPage {
            get {
                return ResourceManager.GetString("SampleTitleRootPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Settings.
        /// </summary>
        public static string SampleTitleThemeDemoSettings {
            get {
                return ResourceManager.GetString("SampleTitleThemeDemoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkthrough.
        /// </summary>
        public static string SampleTitleWalkthrough {
            get {
                return ResourceManager.GetString("SampleTitleWalkthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkthrough Flat.
        /// </summary>
        public static string SampleTitleWalkthroughFlat {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkthrough Variant.
        /// </summary>
        public static string SampleTitleWalkthroughVariant {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string SampleUserProfile {
            get {
                return ResourceManager.GetString("SampleUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a name.
        /// </summary>
        public static string SearchBarPlaceholderSearchForAName {
            get {
                return ResourceManager.GetString("SearchBarPlaceholderSearchForAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string StringAddress {
            get {
                return ResourceManager.GetString("StringAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string StringAddress1 {
            get {
                return ResourceManager.GetString("StringAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string StringAddress2 {
            get {
                return ResourceManager.GetString("StringAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string StringApply {
            get {
                return ResourceManager.GetString("StringApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batman&apos;s choice.
        /// </summary>
        public static string StringBatmanChoice {
            get {
                return ResourceManager.GetString("StringBatmanChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string StringBuy {
            get {
                return ResourceManager.GetString("StringBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call the experts.
        /// </summary>
        public static string StringCallTheExperts {
            get {
                return ResourceManager.GetString("StringCallTheExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reach your current location.
        /// </summary>
        public static string StringCantReachLocation {
            get {
                return ResourceManager.GetString("StringCantReachLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string StringCardNumber {
            get {
                return ResourceManager.GetString("StringCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string StringCategoryArticles {
            get {
                return ResourceManager.GetString("StringCategoryArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string StringCategoryDashboards {
            get {
                return ResourceManager.GetString("StringCategoryDashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECommerce.
        /// </summary>
        public static string StringCategoryECommerce {
            get {
                return ResourceManager.GetString("StringCategoryECommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins.
        /// </summary>
        public static string StringCategoryLogins {
            get {
                return ResourceManager.GetString("StringCategoryLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string StringCategoryMessages {
            get {
                return ResourceManager.GetString("StringCategoryMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string StringCategoryNavigation {
            get {
                return ResourceManager.GetString("StringCategoryNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string StringCategorySocial {
            get {
                return ResourceManager.GetString("StringCategorySocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string StringCategoryTheme {
            get {
                return ResourceManager.GetString("StringCategoryTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkthroughs.
        /// </summary>
        public static string StringCategoryWalkthroughs {
            get {
                return ResourceManager.GetString("StringCategoryWalkthroughs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string StringCity {
            get {
                return ResourceManager.GetString("StringCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clare Japi.
        /// </summary>
        public static string StringClareJapi {
            get {
                return ResourceManager.GetString("StringClareJapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string StringColon {
            get {
                return ResourceManager.GetString("StringColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string StringCompare {
            get {
                return ResourceManager.GetString("StringCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string StringConfirmation {
            get {
                return ResourceManager.GetString("StringConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Your Account.
        /// </summary>
        public static string StringConnectYourAccount {
            get {
                return ResourceManager.GetString("StringConnectYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string StringContact {
            get {
                return ResourceManager.GetString("StringContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Context Action Tapped.
        /// </summary>
        public static string StringContextActionTapped {
            get {
                return ResourceManager.GetString("StringContextActionTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string StringCountry {
            get {
                return ResourceManager.GetString("StringCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ?.
        /// </summary>
        public static string StringCustom {
            get {
                return ResourceManager.GetString("StringCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC.
        /// </summary>
        public static string StringCVC {
            get {
                return ResourceManager.GetString("StringCVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string StringDark {
            get {
                return ResourceManager.GetString("StringDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkTheme.
        /// </summary>
        public static string StringDarkTheme {
            get {
                return ResourceManager.GetString("StringDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string StringDone {
            get {
                return ResourceManager.GetString("StringDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string StringEmail {
            get {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise.
        /// </summary>
        public static string StringEnterprise {
            get {
                return ResourceManager.GetString("StringEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterpriseTheme.
        /// </summary>
        public static string StringEnterpriseTheme {
            get {
                return ResourceManager.GetString("StringEnterpriseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string StringExpirationDate {
            get {
                return ResourceManager.GetString("StringExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra soft UI flavor.
        /// </summary>
        public static string StringExtraSoftUIFlavor {
            get {
                return ResourceManager.GetString("StringExtraSoftUIFlavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string StringFacebook {
            get {
                return ResourceManager.GetString("StringFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish!.
        /// </summary>
        public static string StringFinish {
            get {
                return ResourceManager.GetString("StringFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIENDS.
        /// </summary>
        public static string StringFriends {
            get {
                return ResourceManager.GetString("StringFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a call.
        /// </summary>
        public static string StringGiveUsACall {
            get {
                return ResourceManager.GetString("StringGiveUsACall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grial.
        /// </summary>
        public static string StringGrial {
            get {
                return ResourceManager.GetString("StringGrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string StringIcons {
            get {
                return ResourceManager.GetString("StringIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impress your boss.
        /// </summary>
        public static string StringImpressYourBoss {
            get {
                return ResourceManager.GetString("StringImpressYourBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string StringLastName {
            get {
                return ResourceManager.GetString("StringLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string StringLight {
            get {
                return ResourceManager.GetString("StringLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightTheme.
        /// </summary>
        public static string StringLightTheme {
            get {
                return ResourceManager.GetString("StringLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin.
        /// </summary>
        public static string StringLinkedin {
            get {
                return ResourceManager.GetString("StringLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string StringLoading {
            get {
                return ResourceManager.GetString("StringLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Tapped.
        /// </summary>
        public static string StringMessageTapped {
            get {
                return ResourceManager.GetString("StringMessageTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More from {0}.
        /// </summary>
        public static string StringMoreFrom {
            get {
                return ResourceManager.GetString("StringMoreFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string StringNew {
            get {
                return ResourceManager.GetString("StringNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string StringNext {
            get {
                return ResourceManager.GetString("StringNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string StringNotification {
            get {
                return ResourceManager.GetString("StringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTOS.
        /// </summary>
        public static string StringPhotos {
            get {
                return ResourceManager.GetString("StringPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email address.
        /// </summary>
        public static string StringPleaseConfirmAddress {
            get {
                return ResourceManager.GetString("StringPleaseConfirmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact support center.
        /// </summary>
        public static string StringPleaseContactSupport {
            get {
                return ResourceManager.GetString("StringPleaseContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string StringPrevious {
            get {
                return ResourceManager.GetString("StringPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready made UI&apos;s for Xamarin.Forms..
        /// </summary>
        public static string StringReadyMadeUIsForXamarin {
            get {
                return ResourceManager.GetString("StringReadyMadeUIsForXamarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richard Stainford.
        /// </summary>
        public static string StringRichardStainford {
            get {
                return ResourceManager.GetString("StringRichardStainford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robert Stainford.
        /// </summary>
        public static string StringRobertStainford {
            get {
                return ResourceManager.GetString("StringRobertStainford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string StringSave {
            get {
                return ResourceManager.GetString("StringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string StringSaveChanges {
            get {
                return ResourceManager.GetString("StringSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screens.
        /// </summary>
        public static string StringScreens {
            get {
                return ResourceManager.GetString("StringScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string StringSend {
            get {
                return ResourceManager.GetString("StringSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string StringShare {
            get {
                return ResourceManager.GetString("StringShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up!.
        /// </summary>
        public static string StringSignUp {
            get {
                return ResourceManager.GetString("StringSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong here.
        /// </summary>
        public static string StringSomethingWrongHere {
            get {
                return ResourceManager.GetString("StringSomethingWrongHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StringState {
            get {
                return ResourceManager.GetString("StringState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string StringSuccess {
            get {
                return ResourceManager.GetString("StringSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tapped on {0}&apos;s message..
        /// </summary>
        public static string StringTappedOnAuthorMessage {
            get {
                return ResourceManager.GetString("StringTappedOnAuthorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tapped on {0} context action..
        /// </summary>
        public static string StringTappedOnContextAction {
            get {
                return ResourceManager.GetString("StringTappedOnContextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string StringTwitter {
            get {
                return ResourceManager.GetString("StringTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.KIT.
        /// </summary>
        public static string StringUIKIT {
            get {
                return ResourceManager.GetString("StringUIKIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string StringUsername {
            get {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string StringWarning {
            get {
                return ResourceManager.GetString("StringWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Grial!.
        /// </summary>
        public static string StringWelcomeToGrial {
            get {
                return ResourceManager.GetString("StringWelcomeToGrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new follower.
        /// </summary>
        public static string StringYouHaveANewFollower {
            get {
                return ResourceManager.GetString("StringYouHaveANewFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new message.
        /// </summary>
        public static string StringYouHaveANewMessage {
            get {
                return ResourceManager.GetString("StringYouHaveANewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account.
        /// </summary>
        public static string StringYourAccount {
            get {
                return ResourceManager.GetString("StringYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string StringZipCode {
            get {
                return ResourceManager.GetString("StringZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string TabItemTextAction {
            get {
                return ResourceManager.GetString("TabItemTextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Tab.
        /// </summary>
        public static string TabItemTextAndroid {
            get {
                return ResourceManager.GetString("TabItemTextAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string TabItemTextComedy {
            get {
                return ResourceManager.GetString("TabItemTextComedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        public static string TabItemTextDrama {
            get {
                return ResourceManager.GetString("TabItemTextDrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string TabItemTextFamily {
            get {
                return ResourceManager.GetString("TabItemTextFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes.
        /// </summary>
        public static string TabItemTextHeroes {
            get {
                return ResourceManager.GetString("TabItemTextHeroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS Tab.
        /// </summary>
        public static string TabItemTextiOS {
            get {
                return ResourceManager.GetString("TabItemTextiOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sci Fi.
        /// </summary>
        public static string TabItemTextSciFi {
            get {
                return ResourceManager.GetString("TabItemTextSciFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UXDIVERS.
        /// </summary>
        public static string UXDIVERS {
            get {
                return ResourceManager.GetString("UXDIVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter required information.
        /// </summary>
        public static string ValidationErrorEnterRequiredInfo {
            get {
                return ResourceManager.GetString("ValidationErrorEnterRequiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This is just a friendly warning.
        /// </summary>
        public static string ValidationWarningOops {
            get {
                return ResourceManager.GetString("ValidationWarningOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        public static string WalkthroughHeaderLearn {
            get {
                return ResourceManager.GetString("WalkthroughHeaderLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Time.
        /// </summary>
        public static string WalkthroughHeaderSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughHeaderSaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WalkthroughHeaderWelcome {
            get {
                return ResourceManager.GetString("WalkthroughHeaderWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn while you do.
        ///Grial has tones of examples for you to play..
        /// </summary>
        public static string WalkthroughTextLearn {
            get {
                return ResourceManager.GetString("WalkthroughTextLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save countless hours of UI design.
        ///Focus on what you do best..
        /// </summary>
        public static string WalkthroughTextSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughTextSaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To a new world of posibilities,
        ///welcome to Grial UI Kit..
        /// </summary>
        public static string WalkthroughTextWelcome {
            get {
                return ResourceManager.GetString("WalkthroughTextWelcome", resourceCulture);
            }
        }
    }
}
